version: '3.8'

services:

  server:
    image: aedm/domain-server
    container_name: domain-server
    restart: unless-stopped
    volumes:
      - ./db:/usr/src/app/db
    ports:
      - "8080:8080"

  webapp:
    image: aedm/domain-webapp
    container_name: domain-webapp
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.21-alpine
    command: sh -c "envsubst '$$SERVER_URL $$WEBAPP_URL' < /etc/tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -t && nginx -g 'daemon off;'"
    ports:
      - "4000:8000"
    restart: unless-stopped
    container_name: dataembassy-nginx
    environment:
      - SERVER_URL=http://server:8080
      - WEBAPP_URL=http://webapp:3000
    volumes:
      - ./proxy/nginx.conf:/etc/tmp/nginx.conf
    depends_on:
      - server
      - webapp

