[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
itertools = "0.10.1"
flate2 = { version = "1.0.22", features = ["zlib-ng-compat"], default-features = false }
actix-web = "3.3.2"
serde = "1.0.130"
serde_json = "1.0.68"
smol_str = "0.1.18"
xz2 = "0.1.6"
seq-macro = "0.3"

[profile.release]
# lto = true