[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
reqwest = { version = "0.11", features = ["json", "stream"] }
chrono = "0.4.19"
futures-util = "0.3.14"
indicatif = "0.16.2"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
